[project]
name = "hinkypunk"
version = "0.1.1"
description = "Lightning-like framework for JAX"
authors = [
  {name="Nick DePalma", email="structure@fastmail.us"},
  {name="Phillip Lippe", email="phillip.lippe@googlemail.com"}
  ]
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.10.0"
license = "MIT"
homepage = "https://github.com/petroglyf/hinkypunk"
packages = [{ include = "hinky" }]
urls = {Repository = "https://github.com/ndepalma/jax-trainer"}

dependencies = [
  "cyclopts (>=4.20)",
  "jax (>=0.4.13)",
  "numpy (>=0.0.0)",
  "optax (>=0.2.5)",
  "altair (>=6.2.0)",
  "orbax-checkpoint (>=0.11.19)",
  "flax (>=0.7.0)",
  "pydantic (>=2.12.5)",
  "datasets (>=4.8.5)",
  "progress_table (>=0.0.0)",
  "dltype",
]

[project.optional-dependencies]
tensorboard = [
  "tensorboard", 
  "tensorboardX"
]
wandb = [
  "wandb"
]

[tool.poetry]
requires-poetry = ">=2.4"


[tool.pyrefly]
project-includes = ["**/*.py*"]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/*venv/**/*",
    "**/.[!/.]*/**/*",
]

[tool.poetry.group.dev.dependencies]
pytest = "*"
pyrefly = ">= 1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = [
    "pytest (>=8.4.2,<9.0.0)"
  ]
dev = [
    "pyrefly (>= 1.2)"
]
